### ISSUE TITLE
Installation does not work

### ISSUE THREAD

**Issue by Programie** [chteufleur/go-xmpp4steam#1]
Is this project still maintained?

I just tried to install it using `go get git.kingpenguin.tk/chteufleur/go-xmpp4steam.git` as described in the readme, but go just hangs forever.

Accessing https://git.kingpenguin.tk/chteufleur/go-xmpp4steam in the browser results in an error 502 Bad Gateway.

**Comment by chteufleur** [comment]
Yes, its still maintained.
My Gitea server was down. It should be OK now.
Tell me if something goes wrong.
